git-commit-message: "docs: re-generating terraform-docs"
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    # sqy-tf-eks

    [![docs](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/techdocs.yml/badge.svg)](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/techdocs.yml)

    ## Intro

    Este repositorio es un modulo de Terraform para crear un cluster de Kubernetes para AWS (EKS). Puedes buscar mas informacion del proyecto en:

    - [En el directorio /docs](./docs/)
    - [En el Backstage de Secuoyas](https://backstage.toolbox.secuoyas.com)

    A continuacion se muestra la documentacion de Terraform generada con [Terraform Docs](https://terraform-docs.io/)
    {{ .Content }}

    <!-- END_TF_DOCS -->