apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secuoyas-tf-eks
  description: Terraform module to create EKS clusters
  annotations:
    github.com/project-slug: Secuoyas-Experience/secuoyas-tf-eks
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/Secuoyas-Experience/secuoyas-tf-eks
      title: Github
      icon: github
    - url: https://backstage.toolbox.secuoyas.com/catalog/default/component/secuoyas-tf-eks/docs
      title: Documentacion
      icon: Article
  tags:
    - k8s
    - terraform
    - helm
      
spec:
  type: library  
  owner: infrastructure
  system: toolbox
  lifecycle: production