site_name: 'secuoyas-k8s'
nav:
  - Home: index.md
  - Clusters: clusters.md
  - AWS: aws.md
  - Monitoring: monitoring.md
  - ArgoCD: argocd.md
  - Tools: tools.md
  - Apps: apps.md
  - Certificates: certs.md
  - Griddo: griddo.md
  - Backups: backups.md
plugins:
 - techdocs-core 