site_name: "secuoyas-tf-eks"

nav:
  - index.md
  - install.md
  - kubeconfig.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .
