apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-database-storage
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: grafana-database-storage
  hostPath:
    path: /tmp/grafana/database