apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./grafana-database-pv.yml
  - ./grafana-pv.yml
patches:
  - target:       
      name: grafana-storage
      namespace: monitoring
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: grafana-storage
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi

  - target:       
      name: grafana-database-pvc
      namespace: monitoring
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: grafana-database-storage
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi

  - target:
      name:  grafana-ingress
      namespace: monitoring
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: grafana.secuoyas.local
