---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  minReadySeconds: 35
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snapshot-controller
    spec:
      containers:
      - args:
        - --v=5
        - --leader-election=true
        image: 590183960087.dkr.ecr.eu-central-1.amazonaws.com/k8s/sig-storage/snapshot-controller:v7.0.1
        imagePullPolicy: IfNotPresent
        name: snapshot-controller
      serviceAccountName: snapshot-controller
