apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: griddo-api-prv-monitoring
  labels:
    team: back
spec:
  selector:
    matchLabels:
      app: griddo-api-prv
  endpoints:
  - port: api
    path: /pm