apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads (excluding daemons)
  ttlSecondsUntilExpired: 604800 # expire nodes after 7 days (in seconds) = 7 * 60 * 60 * 24
  limits:
    resources:
      cpu: 32 # limit to 32 CPU cores (each a1.medium == 8 => up to 4 EC2 nodes)
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - "t3a.medium"
  providerRef:
    name: default