apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: example
spec:
  template:
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - "t3.medium"
        - key: "karpenter.sh/capacity-type"
          operator: In
          values:
            - "on-demand"
      nodeClassRef:
        name: default
  limits:
    cpu: "2"
    memory: "8Gi"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s # scale down nodes after 60 seconds without workloads (excluding daemons)
    expireAfter: 168h # expire nodes after 7 days = 7 * 24h