name: 'docs'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"

jobs:
  techdocs:
    runs-on: toolbox-secuoyas
    name: techdocs
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: Secuoyas-Experience/gha-backstage-docs@v1
        with:
          aws_bucket: ${{ secrets.AWS_BUCKET_BACKSTAGE }}
          aws_region: ${{ secrets.AWS_REGION_BACKSTAGE }}
          aws_role_to_assume_arn: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN_BACKSTAGE }}

  terraform-docs:
    runs-on: toolbox-secuoyas
    name: terraform-docs
    needs:
      - techdocs
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.email "mario.garcia@secuoyas.com"
          git config --global user.name "Devops Team"      
      - uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          git-push: "true"