name: 'docs'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"

jobs:
  techdocs:
    runs-on: toolbox-secuoyas
    name: techdocs
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: Secuoyas-Experience/gha-backstage-docs@v3
        with:
          aws_bucket: ${{ secrets.AWS_BUCKET_BACKSTAGE }}
          aws_region: ${{ secrets.AWS_REGION_BACKSTAGE }}
          aws_role_to_assume_arn: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN_BACKSTAGE }}

  terraform-docs:
    runs-on: toolbox-secuoyas
    name: terraform-docs
    needs:
      - techdocs
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.email "mario.garcia@secuoyas.com"
          git config --global user.name "Devops Team"      
      - uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          git-push: "true"
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: re-generating terraform-docs"
          template: |
            <!-- BEGIN_TF_DOCS -->
            # sqy-tf-eks

            [![docs](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/docs.yaml/badge.svg)](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/docs.yaml)
            [![main](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/main.yaml/badge.svg)](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/main.yaml)

            ## Intro

            Este repositorio es un modulo de Terraform para crear un cluster de Kubernetes para AWS (EKS). Puedes buscar mas informacion del proyecto en:

            - [En el directorio /docs](./docs/)
            - [En el Backstage de Secuoyas](https://backstage.toolbox.secuoyas.com)

            A continuacion se muestra la documentacion de Terraform generada con [Terraform Docs](https://terraform-docs.io/)
            {{ .Content }}

            <!-- END_TF_DOCS -->