name: 'docs'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"

jobs:
  techdocs:
    runs-on: ubuntu-latest
    name: techdocs
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: Secuoyas-Experience/gha-backstage-docs@v3
        with:
          aws_bucket: ${{ secrets.AWS_BUCKET_BACKSTAGE }}
          aws_region: ${{ secrets.AWS_REGION_BACKSTAGE }}
          aws_role_to_assume_arn: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN_BACKSTAGE }}