name: 'main'
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - ".github/workflows/docs.yml"

jobs:
  main:
    name: main
    runs-on: toolbox-secuoyas
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setting Git Globals
        run: |
          git config --global user.email "systems@secuoyas.com"
          git config --global user.name "Devops Team"
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Versioning & Pushing New Tag
        run: |
          npx standard-version
          git push
          git push --tags
      - name: Extract Latest Tag
        run: echo "tag=$(git tag -l | tail -n 1)" >> $GITHUB_OUTPUT
        id: latest_tag
      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          git-push: "true"
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: re-generating terraform-docs"
          template: |
            <!-- BEGIN_TF_DOCS -->
            # sqy-tf-eks

            [![docs](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/docs.yaml/badge.svg)](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/docs.yaml)
            [![main](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/main.yaml/badge.svg)](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/main.yaml)
            ![version](https://img.shields.io/badge/version-${{ steps.latest_tag.outputs.tag }}-blue)

            ## Intro

            Este repositorio es un modulo de Terraform para crear un cluster de Kubernetes para AWS (EKS). Puedes buscar mas informacion del proyecto [en el directorio /docs](./docs/).
            A continuacion se muestra la documentacion de Terraform generada con [Terraform Docs](https://terraform-docs.io/)
            {{ .Content }}

            <!-- END_TF_DOCS -->