name: 'main'
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - ".github/workflows/docs.yml"

jobs:
  main:
    name: main
    runs-on: toolbox-secuoyas
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.email "systems@secuoyas.com"
          git config --global user.name "Devops Team"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npx standard-version
      - run: git push
      - run: git push --tags