name: Push main
on:
  push:
    branches:
      - main
  workflow_dispatch:

env: 
  cluster_domain : ${{ secrets.CLUSTER_DOMAIN }} 
  cluster_region : ${{ secrets.CLUSTER_REGION }} 
  cluster_name : ${{ secrets.CLUSTER_NAME }} 
  cluster_kubernetes_version : ${{ secrets.CLUSTER_KUBERNETES_VERSION }} 
  organization : ${{ secrets.ORGANIZATION }}
  environment : ${{ secrets.ENVIRONMENT }} 

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::756537058243:role/GriddoGithubCanExecTF_role
          role-session-name: terraformPlanning
          aws-region: eu-central-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: TF init
        run: terraform init
      - name: TF check
        run: terraform fmt -check
      - name: TF validate
        run: terraform validate
      - name: TF plan
        timeout-minutes: 15
        run: terraform plan
      - name: TF apply
        id: tfapply
        run: terraform apply -auto-approve
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.23.0
        if: steps.tfapply.outcome == 'success'
        with:
          payload: '{"text": "🎉  Aplicado correctamente el plan en secuoyas-tf-eks"}'
        env:
          #TODO: poner este valor en un secret
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
