name: 'main'
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - ".github/workflows/docs.yml"

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setting Git Globals
        run: |
          git config --global user.email "systems@secuoyas.com"
          git config --global user.name "Devops Team"
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Versioning & Pushing New Tag
        run: |
          npx standard-version
          git push
          git push --tags
      - name: Extract Latest Tag
        run: echo "tag=$(git tag -l | tail -n 1)" >> $GITHUB_OUTPUT
        id: latest_tag
      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          git-push: "true"
          output-file: README.md
          output-method: inject
          recursive: true
          git-commit-message: "docs: re-generating terraform-docs"
          template: |
            <!-- BEGIN_TF_DOCS -->
            # sqy-tf-eks

            [![docs](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/docs.yaml/badge.svg)](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/docs.yaml)
            [![main](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/main.yaml/badge.svg)](https://github.com/Secuoyas-Experience/sqy-tf-eks/actions/workflows/main.yaml)
            ![version](https://img.shields.io/badge/version-${{ steps.latest_tag.outputs.tag }}-blue)

            ## Intro

            Este repositorio es un modulo de Terraform para crear un cluster de Kubernetes para AWS (EKS). Puedes buscar mas informacion del proyecto [en el directorio /docs](./docs/).

            ## Ejemplo

            ```ruby
            module "cluster" {
              source                     = "git@github.com:Secuoyas-Experience/sqy-tf-eks.git?ref=1.8.0"
              cluster_name               = "my-domain-es"
              cluster_kubernetes_version = "1.29"
              cluster_cidr               = "10.0.0.0/16"
              cluster_region             = "eu-central-1"
              cluster_azs                = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
              cluster_private_subnets    = ["10.0.0.0/18", "10.0.64.0/18", "10.0.128.0/24"]
              cluster_public_subnets     = ["10.0.192.0/24", "10.0.193.0/24", "10.0.194.0/24"]
              inception_min_size         = 1
              inception_max_size         = 1
              inception_desired_size     = 1
              environment                = "dev"
              organization               = "my.domain.es"
            }
            ```

            A continuacion se muestra la documentacion de Terraform generada con [Terraform Docs](https://terraform-docs.io/)

            {{ .Content }}

            <!-- END_TF_DOCS -->