name: secuoyas-k8s

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/techdocs.yml"

jobs:
  build-docs:
    name: Building TechDocs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install techdocs-cli
        shell: bash
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        shell: bash
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Install additional plugins
        if: inputs.additional-plugins != ''
        shell: bash
        run: |
          for p in ${{ inputs.additional-plugins }}
          do
            python -m pip install $p
          done

      - name: Generate docs site
        shell: bash
        run: techdocs-cli generate --no-docker --verbose

      - name: Upload techdocs artifact
        uses: actions/upload-artifact@v3
        with:
          name: techdocs
          path: site
          retention-days: 1

  upload-docs:
    name: Upload to S3
    needs: build-docs
    runs-on: ubuntu-20.04
    container:
      image: amazon/aws-cli:2.11.18
    permissions:
      id-token: write    
      contents: read
    steps:
      - name: Download techdocs artifact
        uses: actions/download-artifact@v3
        with:
          name: techdocs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: techdocs-uploader-session

      - name: Upload to S3
        run: |
          ls -l
          aws s3 sync . ${{ secrets.AWS_BUCKET }}/toolbox-k8s
