name: secuoyas-k8s

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/techdocs.yml"

jobs:
  publish-techdocs-site:
    name: Publish TechDocs Site
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install techdocs-cli
        shell: bash
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        shell: bash
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Install additional plugins
        if: inputs.additional-plugins != ''
        shell: bash
        run: |
          for p in ${{ inputs.additional-plugins }}
          do
            python -m pip install $p
          done

      - name: Generate docs site
        shell: bash
        run: techdocs-cli generate --no-docker --verbose