name: secuoyas-k8s

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/techdocs.yml"

jobs:
  publish-techdocs-site:
    name: Publish TechDocs Site
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install techdocs-cli
        shell: bash
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        shell: bash
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Install additional plugins
        if: inputs.additional-plugins != ''
        shell: bash
        run: |
          for p in ${{ inputs.additional-plugins }}
          do
            python -m pip install $p
          done

      - name: Fix docs not created
        run: |
          pwd
          ls -l
          mkdir -p docs

      - name: Generate docs site
        shell: bash
        run: techdocs-cli generate --no-docker --verbose

      - name: Check generated files
        run: |
          ls -l docs
          ls -l site